"""
Settings for Biz
"""
from lms.envs.aws import AUTH_TOKENS, ENV_TOKENS, CELERY_DEFAULT_QUEUE
from lms.envs.common import (
    BIZ_MONGO,
    MAX_RETRY_REMOVE_DOCUMENTS,
    SLEEP_RETRY_REMOVE_DOCUMENTS,
    MAX_RETRY_SET_DOCUMENTS,
    SLEEP_RETRY_SET_DOCUMENTS,
    AGGREGATE_FETCH_LIMIT,
    BIZ_FROM_EMAIL,
    BIZ_RECIPIENT_LIST,
    BIZ_MAX_REGISTER_NUMBER,
    BIZ_MAX_CHAR_LENGTH_REGISTER_LINE,
    BIZ_MAX_BULK_STUDENTS_NUMBER,
    BIZ_MAX_CHAR_LENGTH_BULK_STUDENTS_LINE,
    BIZ_MAX_REGISTER_ADDITIONAL_INFO,
    BIZ_MAX_CHAR_LENGTH_REGISTER_ADD_INFO_LINE,
)


"""
Basic Settings
"""
BIZ_SECRET_KEY = AUTH_TOKENS['BIZ_SECRET_KEY']

"""
MongoDB
"""
BIZ_MONGO = AUTH_TOKENS.get('BIZ_MONGO', BIZ_MONGO)
BIZ_MONGO_LIMIT_RECORDS = ENV_TOKENS.get('BIZ_MONGO_LIMIT_RECORDS', 0)

"""
Batch Settings
"""
BIZ_SET_SCORE_COMMAND_OUTPUT = ENV_TOKENS.get('BIZ_SET_SCORE_COMMAND_OUTPUT')
BIZ_SET_SHOW_ENABLED_CONTRACT_COMMAND_OUTPUT = ENV_TOKENS.get('BIZ_SET_SHOW_ENABLED_CONTRACT_COMMAND_OUTPUT')
BIZ_SET_PLAYBACK_COMMAND_OUTPUT = ENV_TOKENS.get('BIZ_SET_PLAYBACK_COMMAND_OUTPUT')
BIZ_SEND_SUBMISSION_REMINDER_COMMAND_OUTPUT = ENV_TOKENS.get('BIZ_SEND_SUBMISSION_REMINDER_COMMAND_OUTPUT')
BIZ_IMPORT_PLAYBACK_LOG_COMMAND_OUTPUT = ENV_TOKENS.get('BIZ_IMPORT_PLAYBACK_LOG_COMMAND_OUTPUT')
MAX_RETRY_REMOVE_DOCUMENTS = ENV_TOKENS.get('MAX_RETRY_REMOVE_DOCUMENTS', MAX_RETRY_REMOVE_DOCUMENTS)
SLEEP_RETRY_REMOVE_DOCUMENTS = ENV_TOKENS.get('SLEEP_RETRY_REMOVE_DOCUMENTS', SLEEP_RETRY_REMOVE_DOCUMENTS)
MAX_RETRY_SET_DOCUMENTS = ENV_TOKENS.get('MAX_RETRY_SET_DOCUMENTS', MAX_RETRY_SET_DOCUMENTS)
SLEEP_RETRY_SET_DOCUMENTS = ENV_TOKENS.get('SLEEP_RETRY_SET_DOCUMENTS', SLEEP_RETRY_SET_DOCUMENTS)
AGGREGATE_FETCH_LIMIT = ENV_TOKENS.get('AGGREGATE_FETCH_LIMIT', AGGREGATE_FETCH_LIMIT)

"""
AWS S3
"""
BIZ_PLAYBACK_LOG_BUCKET_NAME = ENV_TOKENS.get('BIZ_PLAYBACK_LOG_BUCKET_NAME')

"""
Celery
"""
BIZ_CELERY_DEFAULT_QUEUE = ENV_TOKENS.get('BIZ_CELERY_DEFAULT_QUEUE', CELERY_DEFAULT_QUEUE)

"""
Monthly report info
"""
BIZ_FROM_EMAIL = ENV_TOKENS.get('BIZ_FROM_EMAIL', BIZ_FROM_EMAIL)
BIZ_RECIPIENT_LIST = ENV_TOKENS.get('BIZ_RECIPIENT_LIST', BIZ_RECIPIENT_LIST)
BIZ_MONTHLY_REPORT_COMMAND_OUTPUT = ENV_TOKENS.get('BIZ_MONTHLY_REPORT_COMMAND_OUTPUT')

"""
Register student
"""
BIZ_MAX_REGISTER_NUMBER = ENV_TOKENS.get('BIZ_MAX_REGISTER_NUMBER', BIZ_MAX_REGISTER_NUMBER)
BIZ_MAX_CHAR_LENGTH_REGISTER_LINE = ENV_TOKENS.get('BIZ_MAX_CHAR_LENGTH_REGISTER_LINE', BIZ_MAX_CHAR_LENGTH_REGISTER_LINE)

"""
Bulk student Management
"""
BIZ_MAX_BULK_STUDENTS_NUMBER = ENV_TOKENS.get('BIZ_MAX_BULK_STUDENTS_NUMBER', BIZ_MAX_BULK_STUDENTS_NUMBER)
BIZ_MAX_CHAR_LENGTH_BULK_STUDENTS_LINE = ENV_TOKENS.get('BIZ_MAX_CHAR_LENGTH_BULK_STUDENTS_LINE', BIZ_MAX_CHAR_LENGTH_BULK_STUDENTS_LINE)

"""
Additional info
"""
BIZ_MAX_REGISTER_ADDITIONAL_INFO = ENV_TOKENS.get('BIZ_MAX_REGISTER_ADDITIONAL_INFO', BIZ_MAX_REGISTER_ADDITIONAL_INFO)
BIZ_MAX_CHAR_LENGTH_REGISTER_ADD_INFO_LINE = ENV_TOKENS.get('BIZ_MAX_CHAR_LENGTH_REGISTER_ADD_INFO_LINE', BIZ_MAX_CHAR_LENGTH_REGISTER_ADD_INFO_LINE)
