"""
Settings for Biz
"""
from lms.envs.aws import AUTH_TOKENS, ENV_TOKENS, CELERY_DEFAULT_QUEUE
from lms.envs.common import BIZ_MONGO


"""
MongoDB
"""
BIZ_MONGO = AUTH_TOKENS.get('BIZ_MONGO', BIZ_MONGO)

"""
Set score Batch Settings
"""
BIZ_SET_SCORE_COMMAND_OUTPUT = ENV_TOKENS.get('BIZ_SET_SCORE_COMMAND_OUTPUT')

"""
Celery
"""
BIZ_CELERY_DEFAULT_QUEUE = ENV_TOKENS.get('BIZ_CELERY_DEFAULT_QUEUE', CELERY_DEFAULT_QUEUE)
