"""
Settings for Biz
"""
from lms.envs.aws import AUTH_TOKENS, ENV_TOKENS, CELERY_DEFAULT_QUEUE
from lms.envs.common import (
    BIZ_MONGO,
    BIZ_FROM_EMAIL,
    BIZ_RECIPIENT_LIST,
    INTERVAL_DAYS_TO_SEND_SUBMISSION_REMINDER_EMAIL,
    BIZ_MAX_REGISTER_NUMBER,
    BIZ_MAX_CHAR_LENGTH_REGISTER_LINE,
    BIZ_MAX_BULK_STUDENTS_NUMBER,
    BIZ_MAX_CHAR_LENGTH_BULK_STUDENTS_LINE,
)


"""
Basic Settings
"""
BIZ_SECRET_KEY = AUTH_TOKENS['BIZ_SECRET_KEY']

"""
MongoDB
"""
BIZ_MONGO = AUTH_TOKENS.get('BIZ_MONGO', BIZ_MONGO)

"""
Batch Settings
"""
BIZ_SET_SCORE_COMMAND_OUTPUT = ENV_TOKENS.get('BIZ_SET_SCORE_COMMAND_OUTPUT')
BIZ_SET_PLAYBACK_COMMAND_OUTPUT = ENV_TOKENS.get('BIZ_SET_PLAYBACK_COMMAND_OUTPUT')
BIZ_SEND_SUBMISSION_REMINDER_COMMAND_OUTPUT = ENV_TOKENS.get('BIZ_SEND_SUBMISSION_REMINDER_COMMAND_OUTPUT')

"""
Celery
"""
BIZ_CELERY_DEFAULT_QUEUE = ENV_TOKENS.get('BIZ_CELERY_DEFAULT_QUEUE', CELERY_DEFAULT_QUEUE)

"""
Monthly report info
"""
BIZ_FROM_EMAIL = ENV_TOKENS.get('BIZ_FROM_EMAIL', BIZ_FROM_EMAIL)
BIZ_RECIPIENT_LIST = ENV_TOKENS.get('BIZ_RECIPIENT_LIST', BIZ_RECIPIENT_LIST)
BIZ_MONTHLY_REPORT_COMMAND_OUTPUT = ENV_TOKENS.get('BIZ_MONTHLY_REPORT_COMMAND_OUTPUT')

"""
Submission reminder email batch
"""
INTERVAL_DAYS_TO_SEND_SUBMISSION_REMINDER_EMAIL = ENV_TOKENS.get('INTERVAL_DAYS_TO_SEND_SUBMISSION_REMINDER_EMAIL', INTERVAL_DAYS_TO_SEND_SUBMISSION_REMINDER_EMAIL)

"""
Register student
"""
BIZ_MAX_REGISTER_NUMBER = ENV_TOKENS.get('BIZ_MAX_REGISTER_NUMBER', BIZ_MAX_REGISTER_NUMBER)
BIZ_MAX_CHAR_LENGTH_REGISTER_LINE = ENV_TOKENS.get('BIZ_MAX_CHAR_LENGTH_REGISTER_LINE', BIZ_MAX_CHAR_LENGTH_REGISTER_LINE)

"""
Bulk student Management
"""
BIZ_MAX_BULK_STUDENTS_NUMBER = ENV_TOKENS.get('BIZ_MAX_BULK_STUDENTS_NUMBER', BIZ_MAX_BULK_STUDENTS_NUMBER)
BIZ_MAX_CHAR_LENGTH_BULK_STUDENTS_LINE = ENV_TOKENS.get('BIZ_MAX_CHAR_LENGTH_BULK_STUDENTS_LINE', BIZ_MAX_CHAR_LENGTH_BULK_STUDENTS_LINE)
